sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
    #redis共16（0-15）个库
    database: 0

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: suncoya-bucket

wechat:
  appid: wxb803c3902495c724
  secret: aeacd9bf2b513ef312bf7011c88605ee