server:
  port: 8080

spring:
  profiles:
    # 使用开发环境下的配置文件，改成prod变为生产环境下的配置文件
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}
  redis:
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    password: ${sky.redis.password}
    #redis共16（0-15）个库
    database: ${sky.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间：2000小时
    admin-ttl: 7200000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

    #用户端生成令牌
    user-secret-key: itcast
    user-ttl: 7200000000
    user-token-name: authentication

  wechat:
    appid: ${wechat.appid}
    secret: ${wechat.secret}

aliyun:
  oss:
    endpoint: ${aliyun.oss.endpoint}
    bucketName: ${aliyun.oss.bucketName}

